#' Install required packages
#' Install all necessary packages for required commands.
#' @export
#' @param () no required parameters
#' @examples
#' Install_required_packages()
#'

Install_required_packages <- function() {

    # library(webinar.cpom)
    install.packages("quantmod")
    install.packages("PerformanceAnalytics")
    install.packages("magrittr")
    install.packages("fBasics")
    install.packages("tidyverse")
    install.packages("stringr")
    install.packages("dplyr")
    install.packages("neuralnet")
    install.packages("zoo")
    install.packages("forecast")
    install.packages("timetk")
    install.packages("moments")
    install.packages("data.table")
    install.packages("ggplot2")
    install.packages("rvest")
    install.packages("caret")
    install.packages("readxl")
    install.packages("writexl")
    install.packages("portfolio.optimization")
    install.packages("PortfolioAnalytics")
    install.packages("ROI")
    install.packages("fPortfolio")
    install.packages("timeSeries")
    install.packages("gridExtra")
    install.packages("cowplot")
    install.packages("portfolioBacktest")
    install.packages("CVXR")
    install.packages("MFDFA")
    install.packages("DEoptim")
    #install.packages("nse2r")
    install.packages('var')
    install.packages('cvar')
    #library("nse2r")
    library("quantmod")
    library("PerformanceAnalytics")
    library("magrittr")
    library("fBasics")
    library("tidyverse")
    library("stringr")
    library("dplyr")
    library("neuralnet")
    library("zoo")
    library("forecast")
    library("timetk")
    library("moments")
    library("data.table")
    library("ggplot2")
    library("rvest")
    library("caret")
    library("readxl")
    library("writexl")
    library("portfolio.optimization")
    library("PortfolioAnalytics")
    library("ROI")
    library("fPortfolio")
    library("timeSeries")
    library("gridExtra")
    library("cowplot")
    library("portfolioBacktest")
    library("CVXR")
    library("MFDFA")
    library("DEoptim")
    library("rvest")
    library("var")
    library("cvar")

  x="All installed and loaded"
  print(x)
}
